//var quizTitle = "Can you guess what’s wrong?";
var qArray = [];
question0 = new Object;
question0.question = "Which correction should be made to the sentence? <br>Neither Andrea nor Caleb will tell what they seen.";
question0.answerArr = ["A: change Neither to Either", "B: change nor to or", "C: change they to he", "D: change seen to saw", "E: both C and D"];
question0.explanation = "Problem: Both answers C and D are needed to make the sentence correct.";
question0.sourced = "Source: Georgia Department of Education";
question0.correct = "E";
qArray.push(question0);
question1 = new Object;
question1.question = "Which factor is MOST closely associated with an increase in the price of a good?";
question1.answerArr = ["increased worker productivity", "increased technological innovations", "increased government price ceilings", "increased competition among buyers", "None of these"];
question1.explanation = "Problem: Poorly worded – performed poorly.";
question1.sourced = "Source: Georgia Department of Education";
question1.correct = "E";
qArray.push(question1);
question2 = new Object;
question2.question = "A construction worker is laid off from his job every winter but is rehired in the spring. What kind of unemployment does the construction worker experience?";
question2.answerArr = ["cyclical", "frictional", "structural", "recessional", "seasonal"];
question2.explanation = "Problem: Has no correct answer. “Seasonal” would have been a better option.";
question2.sourced = "Source: Georgia Department of Education";
question2.correct = "E";
qArray.push(question2);
question3 = new Object;
question3.question = "Andrew Lloyd Webber’s occupation is:";
question3.answerArr = ["Playwright", "Painter", "Sculptor", "Athlete", "Composer\/producer"];
question3.explanation = "Problem: No correct answer. Webber is a composer and producer.";
question3.sourced = "Source: CTB McGraw-Hill e-mail/Georgia Department of Education. Question is paraphrased based on documents obtained from the state.";
question3.correct = "E";
qArray.push(question3);
